name: Deploy the site

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: "Environment to deploy to"
        required: true
        default: "production"

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: SKIP_POST_INSTALL=1 yarn install
      - name: Build
        run: PUBLIC_BASE_URL="${{ vars.BASE_URL }}" yarn build
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      - name: Deploy to Admin S3
        run: aws s3 sync --acl public-read --delete ./dist/ s3://${{ vars.S3_BUCKET_NAME }}
      - name: Invalidate CloudFront cache
        run: aws cloudfront create-invalidation --paths '/*' --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION_ID }}
