name: Deploy main branch to production

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: production
